### ISSUE TITLE
Ecryptfs 관련 질문

### ISSUE THREAD

**Issue by patnh2** [somansa-oss/endpointdlp#21]
안녕하세요?
구름OS에서 실행해 보면 PIKern 모듈에서 가져오는 파일 시스템 이벤트의 파일 경로는 암호화되어 있습니다.
파일 경로를 플레인 텍스트로 볼 수 있는 방법이 없을까요?

**Comment by lovenamu** [comment]
안녕하세요
혹시 아래 질문 관련해서, PIKern 내의 관련 소스 위치가 어떻게 될지요?
실제 디버깅 해보면, 파일 경로가 암호화되지 않은 것으로 파악이 되어서 입니다.

> PIKern 모듈에서 가져오는 파일 시스템 이벤트의 파일 경로는 암호화되어 있습니다.

감사합니다

**Comment by patnh2** [comment]
ecryptfs가 동작 중일 때는 암호화되어 있고 삭제 후 해보면 플레인 텍스트로 나옵니다.
참고로 OS 버전은 구름 2.0입니다.

PIESF.cpp

static int
event_process (struct fanotify_event_metadata *event,
               int                             fanotify_fd,
               char *file_path)
...
printf("targe_file_path-[%s]\n", target_file_path.c_str());

**Comment by lovenamu** [comment]
의견 주셔서 감사합니다
ecryptfs 관련해서는 아직 검증 안된 것으로 예상됩니다.
혹시, 구름OS를 도입하려는 고객사에서 encryptfs 사용이 필요인 상황인지요?

**Comment by patnh2** [comment]
구름OS 설치 시 기본적으로 ecryptfs 사용을 권장해서 여쭤봤습니다.
답변 감사합니다!

**Comment by lovenamu** [comment]
네 
앞으로 개발에 참고하겠습니다
의견 주셔서 감사합니다
